### ISSUE TITLE
ZipN edge cases & performance

### ISSUE THREAD

**Issue by buybackoff** [Spreads/Spreads#1]
- [x] MP continuous was not fixed after MN was. Also, MoveAt is wrong, it needs special treatment for continuous and semi-continuous cases compared to MF/ML.
- [x] ~~We should still assume that continuous ZipN is likely broken. Given that it is inherently non deterministic and slow and non needed frequently, that was not a priority. Must rework ZipN togetehr with #10~~
- [x] We need Series and Cursors implement IObservable at least. Also return to the idea of reactive streams.
- [x] Out of order data handling and new data notifications are easier with IObservable #14
- [ ] For continuous case, performance requires a lot of work. TGV optimizations from #27 and probably assigning values when moving cursors.
- [ ] Make ZipN parallel for large N. Could use shared values array with offset/len and ZipN over ZipNs. 
- [ ] Rename ZipN that works over buffer **ZipUnsafe**, for safe version allocate a temp buffer ~~or even better user _Span<T>_, which will be stack-only (whatever it means, hopefully lambda could then be applied to it but then the reference to data cannot escape the context)~~ (span won't work here)

_NB_ ZipN(ZipN(x), ZipN(y)) is equivalent to ZipN(x + y) (!?) Think about some optimizations with pivots/discrete series, e.g. calculating key union on one thread and evaluating zipped result on another (even several of them).

**Comment by buybackoff** [comment]
ZipN was not properly optimized, especially the continuous moves. There are wasteful and repeated operations.
Also, we must delay calling CurrentValue until we are sure that keys are OK. E.g. in BindCursor CurrentValue is lazy. With `ICanMapValues` optimization that laziness could be deep.

**Comment by buybackoff** [comment]
We should still assume that continuous ZipN is likely broken. Given that it is inherently non deterministic and slow and non needed frequently, that was not a priority. Must rework ZipN togetehr with #10

**Comment by buybackoff** [comment]
We need Series and Cursors implement IObservable at least. Also return to the idea of reactive streams.

**Comment by buybackoff** [comment]
* [ ] For continuous case, performance requires a lot of work. TGV optimizations from #27 and probably assigning values when moving cursors.

**Comment by buybackoff** [comment]
v.0.3 fixed known bugs and now ZipN looks mostly correct

**Comment by buybackoff** [comment]
* [ ] #100 SortedDeque and FixedMaxHeap should have a specialized implementation for most common key types. We could even manually inline comparisons. ZipN for `DateTime` and `long` should also be specialized

**Comment by buybackoff** [comment]
Old ZipN implementation is deprecated in favor of the new Zip (Zip2) one. ZipN should be implemented by applying Zip2 in a fold-like manner.

This very first issue could be closed for good. #108 tracks Zip and other cursors implementation.
