### ISSUE TITLE
Memory Allocations: Know Your Enemy

### ISSUE THREAD

**Issue by buybackoff** [Spreads/Spreads#34]
#### TODOs
* [x] ~~Do not use F# tuple expansion as per #32~~ (it is already [optimized](https://github.com/Microsoft/visualfsharp/pull/335) in F#, not sure if it is already in F# 3.1.2.5)
* [x] Do not use F# ref cells if possible (done in SM)
* [x] Static constructor in base untyped Series is called many times
* [x] F# Option use should be eliminated even in constructors
* [x] Check generated IL for OnCompleted, OnMoved (in ZipN MNA) and other [nested functions](http://stackoverflow.com/questions/35042627/how-does-nesting-f-functions-differ-from-not-nesting-them-when-nesting-is-optio).
...

#### Readme index example memory profiling
Preallocated capacity: DateTime has 1000 allcoations - initially we allocate DT[2] for regular keys, that could be just fields.

Double[] is allocated exactly 501 time - 500 for series and 1 for ZipN vArr.

F# ref cells are the main enemy now.

Most numbers that are multiples of 500x are allocated for the entire lifetime of the test. This pic proves the point that Spreads library does not generate garbage.

![image](https://cloud.githubusercontent.com/assets/489852/12460936/580a2cc6-bfc7-11e5-8f95-bb41059c5f3a.png)

**Comment by scifral** [comment]
Regarding ref cells, one thing that can help is to move to F# 4.4/ .Net 4.6.
Re. the [F# 4.0 preview announcement ] ( http://blogs.msdn.com/b/fsharpteam/archive/2014/11/12/announcing-a-preview-of-f-4-0-and-the-visual-f-tools-in-vs-2015.aspx) :  "With F# 4.0, developers can now just use the ‘mutable’ keyword for all mutable values, and the compiler will take care of the rest, creating a stack-based value if possible, otherwise implicitly converting to a ref cell". 
Meanwhile, great work on these memory issues today. -Steve

**Comment by buybackoff** [comment]
@scifral  Most of ref cells are in object expressions like GetCursor in SortedMap. It looks like changing ref to mutable variables already works with the current version in Spreads. It doesn't work with closures, etc.

**Comment by buybackoff** [comment]
Mutable locals are converted to ref cell implicitly in object expressions. Need to create a separate class in the same way as the struct cursor. The idea is that mutable series and their cursors are usually created for lifetime of process and an we could safely allocate objects for this. For chunks and temporal allocations or for `foreach` loops we always use struct cursors.

**Comment by buybackoff** [comment]
Events, threadlocals look not good. Also atomic counters do not equal to buffers
![image](https://cloud.githubusercontent.com/assets/489852/14564348/d7faed76-032e-11e6-8871-08cd7c627408.png)

**Comment by buybackoff** [comment]
It is just matter of hygiene and running profilers and PerfView regularly, no longer a separate issue.
